
public class Exception1
{

public static void main(String[] args) {
	try
	{
		int c=10/2;
		System.out.println(c);
		
	}
	
	catch(Exception e)
	{
		System.out.println("from exception");
	}
	
	finally
	{
		System.out.println("from finally");
	}
	
	
	
	

 
	  }
}